-- phpMyAdmin SQL Dump
-- version 4.8.4
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1:3306
-- Generation Time: Jun 03, 2019 at 09:48 AM
-- Server version: 5.7.24
-- PHP Version: 7.2.14

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `jpublankproject`
--

DELIMITER $$
--
-- Procedures
--
DROP PROCEDURE IF EXISTS `getLevel`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `getLevel` (IN `_levelID` INT)  READS SQL DATA
    SQL SECURITY INVOKER
    COMMENT 'non'
SELECT * FROM leveltable WHERE leveltable.levelID = _levelID$$

DELIMITER ;

-- --------------------------------------------------------

--
-- Table structure for table `leveltable`
--

DROP TABLE IF EXISTS `leveltable`;
CREATE TABLE IF NOT EXISTS `leveltable` (
  `levelID` int(11) NOT NULL AUTO_INCREMENT,
  `highScore` int(11) NOT NULL,
  `levelAsTxt` text CHARACTER SET utf8 NOT NULL,
  `maxTimeToDoLevel` int(11) NOT NULL DEFAULT '500',
  `minDiams` int(11) NOT NULL DEFAULT '5',
  PRIMARY KEY (`levelID`)
) ENGINE=MyISAM AUTO_INCREMENT=9 DEFAULT CHARSET=latin1;

--
-- Dumping data for table `leveltable`
--

INSERT INTO `leveltable` (`levelID`, `highScore`, `levelAsTxt`, `maxTimeToDoLevel`, `minDiams`) VALUES
(1, 5, 'ttttttttttttttttttttttttttttmttttttttttttttttttttttttttttttt\r\ntttttttttttttttttttttttttttmtmtttttttttttttttttttttttttttttt\r\ntttrttttttrrttttttttttttttmtttmtttttttttttrrrrtttttttttrtttt\r\nttttttrtttrrtttttttttttttmtttttmttttttttttrrttttttrttrtttttt\r\nttttttttttttttttttrrtttrmttrrrttmttttrtrtttttdttttttrttttttt\r\nttttrtttttrttttttttttttmmmmmmmmmmmttttrtrrrtrtrtttrrtttttttt\r\ntccctttttcccttttctrtttmttttrttrtttmttttcttcctttttccttttttttt\r\nttttrrrrrtrttttttttccmtcttrctcrtcrcmtttcttttttctctcttttttttt\r\nttttttttttz######################################wtttttttttt\r\ntttmmrttttattttttcttdtrctttttrtrtttttttcttttrttttjtttttttttt\r\nttttttttttatrsrttttttctttttttttrdttrttttctttttcttjtttrrttttt\r\nttttttttttattttttttttcttrtttttrtrttrttttttttrttttjtttttttttt\r\ntttttmttttartrrtttttttttrttttttrttrttttrtttrtttttjtttttcrttt\r\nttttmtmtttartcrtttttttttcrttrttttttttrttttttrtrrtjtrcttttttt\r\ntttmmmmmttatttcttrttttttttrtttttrtcrttttttttrtrrtjttmttttttt\r\nttmrttttmtammmmmmmmmmmmmmmmmmmmmmmmmmmmmmtttrttrtjtttttccttt\r\ntmtttttttmatctttrttdtcttrtrttttttttttdtrdttttttctjtttttttttt\r\ntrrrttttttattdtttttrtttttcttttttttrrcrttrttttrtttjtttttttttt\r\nttttttttddatttrttrtrttttttttttttttrctrttrttttttttjtttttttttt\r\ntttttcrtttatrtttttrttttttttrrrtttttttrttctdttttrtjttcrtttttt\r\ntttcctttttatdttcttrtcctttttrtrdttdttttrtttrttdtctjttttrrtttt\r\nttttttttttatcrttttttttttttttrcrttrttttttttdtttttrjtttttttttt\r\nttttttttttattttttttmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmjtttmmmtttt\r\nttttttttttacrtttttttttrtttdttttrtttttrtttrtttttttjtttttttttt\r\nttttrdttttacrtttttttttcrttrttttttttrttttttrtrrttxjtttdtttttt\r\nttttttttttatcttrttttttttrtttttrtccttttdtttrtrrtttjtctttttttt\r\nttttttdcttattttrdttrttttttttrttttttrtrdttttttrtttjttttmrtttt\r\nttttttttttatttcttrtcttrtrrtttttttttrtrdttttttcttrjtt#ttttttt\r\nttttcttdttatdttttctttttctttttttttctrttrttttrtttrtjtttmtttttt\r\ntttttttttto######################################ktmtctttttt\r\ntttttttttttttddtttttttttttttmttttttttddttttttttttttttttttttt\r\ntttttttttttttttttttttttttttmtmtttttttttttttttttttttttttttttt\r\ntttrttttttrrttttttttttttttmtttmtttttttttttrrrrtttttttttrtttt\r\nttttttrtttrrtttttttttttttmtttttmttttttttttrrttttttrttrtttttt\r\nttttttttttttttttttrrtttrmttrrrttmttttrtrtttttdttttttrttttttt\r\nttttrtttttrttttttttttttmmmmmmmmmmmttttrtrrrtrtrtttrrtttttttt\r\ntccctttttcccttttctrtttmttttrttrtttmttttcttcctttttccttttttttt\r\nttttrrrrrtrttttttttccmtcttrctcrtcrcmtttcttttttctctcttttttttt\r\n', 150, 12),
(2, 5, 'ttttttttttttttttttttttttttttmttttttttttttttttttttttttttttttt\r\ntttttttttttttttttttttttttttmtmtttttttttttttttttttttttttttttt\r\ntttrttttttrrttttttttttttttmtttmtttttttttttrrrrtttttttttrtttt\r\nttttttrtttrrtttttttttttttmtttttmttttttttttrrttttttrttrtttttt\r\nttttttttttttttttttrrtttrmttrrrttmttttrtrtttttdttttttrttttttt\r\nttttrtttttrttttttttttttmmmmmmmmmmmttttrtrrrtrtrtttrrtttttttt\r\ntccctttttcccttttctrtttmttttrttrtttmttttcttcctttttccttttttttt\r\nttttrrrrrtrttttttttccmtcttrctcrtcrcmtttcttttttctctcttttttttt\r\nttttttttttz######################################wtttttttttt\r\ntttmmrttttatrttrttmtrtttdtmtttxtrtmcttttttmttrrttjtttttttttt\r\nttttttttttatttttttmttttttcmcctrtttmcttctttmttttctjtttrrttttt\r\nttttttttttaccccccccccccccrcrrccccccrccdccccccccrcjtttttttttt\r\ntttttmttttadttttttmtrttttrmtrtcttcmttrttdtmttrtrtjtttttcrttt\r\nttttmtmtttatttttttmtrttttrmtrtccttmtttttrtmtttcttjtrcttttttt\r\ntttmmmmmttammmmmmmmmmmmmmmmmmmcmmmmmmmmmmmmmmmmmmjttmttttttt\r\nttmrttttmtattttrrtmttcttttmtttcttrmttttcttmtttttcjtttttccttt\r\ntmtttttttmatttttttmttcttttmtttctttmttttrtcmtttttrjtttttttttt\r\ntrrrttttttaccccccccccrcccccccccccccccccrccccccccrjtttttttttt\r\nttttttttddarttrtttmttttrttmttrctttmttttttdmctttttjtttttttttt\r\ntttttcrtttarttttrtmttrttrtmtttctccmtttttttmrtttrtjttcrtttttt\r\ntttcctttttatrtttttmtttrtttmtttctrrmtttttttmrrttrtjttttrrtttt\r\ntttttrrtttammmmmmmmmmmmmmmmmmmcmmmmmmmmmmmmmmmmmmjtttttttttt\r\nttttttttttarteccttmttttrtrmtttctttmtrdttrtmttttttjtttmmmtttt\r\nttttttttttatccccctmcttttttmttcctttmcttctttmtctcctjtttttttttt\r\nttttrdttttaccccccccrcccccccccdccccccccrcccccrcrrcjtttdtttttt\r\nttttttttttadttctrtmrttttrtmtrtcttrmtrtrtttmttttttjtctttttttt\r\nttttttdcttatttttrtmrttdtttmtttccttmttrttttmtttcccjttttmrtttt\r\nttttttttttatdtttrcmttcttttmtsdcrttmtctttttmtttrrrjtt#ttttttt\r\nttttcttdttatrttttrmttrttrtmt#trtttmttttrtrmttttrtjtttmtttttt\r\ntttttttttto######################################ktmtctttttt\r\ntttttttttttttddtttttttttttttmttttttttddttttttttttttttttttttt\r\ntttttttttttttttttttttttttttmtmtttttttttttttttttttttttttttttt\r\ntttrttttttrrttttttttttttttmtttmtttttttttttrrrrtttttttttrtttt\r\nttttttrtttrrtttttttttttttmtttttmttttttttttrrttttttrttrtttttt\r\nttttttttttttttttttrrtttrmttrrrttmttttrtrtttttdttttttrttttttt\r\nttttrtttttrttttttttttttmmmmmmmmmmmttttrtrrrtrtrtttrrtttttttt\r\ntccctttttcccttttctrtttmttttrttrtttmttttcttcctttttccttttttttt\r\nttttrrrrrtrttttttttccmtcttrctcrtcrcmtttcttttttctctcttttttttt\r\n', 150, 9),
(3, 5, 'tttttttttttttddtttttttttttttmttttttttddttttttttttttttttttttt\r\ntttttttttttttttttttttttttttmtmtttttttttttttttttttttttttttttt\r\ntttrttttttrrttttttttttttttmtttmtttttttttttrrrrtttttttttrtttt\r\nttttttrtttrrtttttttttttttmtttttmttttttttttrrttttttrttrtttttt\r\nttttttttttttttttttrrtttrmttrrrttmttttrtrtttttdttttttrttttttt\r\nttttrtttttrttttttttttttmmmmmmmmmmmttttrtrrrtrtrtttrrtttttttt\r\ntccctttttcccttttctrtttmttttrttrtttmttttcttcctttttccttttttttt\r\nttttrrrrrtrttttttttccmtcttrctcrtcrcmtttcttttttctctcttttttttt\r\nttttttttttz######################################wtttttttttt\r\ntttmmrttttartmmtmrrtmtttrmrttrttttmtttrtttttrmtdtjtttttttttt\r\nttttttttttattsmtdtrtmtttmmmttmtrttttrttrtrtttmtmrjtttrrttttt\r\nttttttttttattttmttrdttrttttmtttttrtmmrtttttttmtmmjtttttttttt\r\ntttttmttttadtmttmrmrttrttttmtttrttttttrtrrttttttmjtttttcrttt\r\nttttmtmtttartmtttmttrtmmttrtmmdtttttttrtrrttttttmjtrcttttttt\r\ntttmmmmmttarrttrttttmtttrttttttrtrrttttttrttdmmttjttmttttttt\r\nttmrttttmtattrtmmttrtrrtttmttttrtrrttttttmttrtmtrjtttttccttt\r\ntmtttttttmattmtttdttttttdtrttmmrttrtmtmrttmrttdtrjtttttttttt\r\ntrrrttttttartrttttmtmmttdtrttmmrttrttdtmtttmttrtmjtttttttttt\r\nttttttttddatrtmmtttttrrmrttdtmtmrttmrtttmrttdtrttjtttttttttt\r\ntttttcrtttamtmmttttttrrmrttrtmtmmtttmttrtmmttrtmmjttcrtttttt\r\ntttcctttttatmtrtrtmtttmmrttrttttmtttrtttttmmtrtmmjttttrrtttt\r\nttttttttttatmtrtrtmtdtmtmrttmrttttrttrtrrttttmtttjtttttttttt\r\nttttttttttamttmrmrttrttttmtttdtttmtrmttttttmtmmtdjtttmmmtttt\r\nttttttttttamtttmmrttmtdtttmrttrtrtttrtmrttttttmttjtttttttttt\r\nttttrdttttamtdttttrtmmttrtmmrtttttttrtmrttttttmttjtttdtttttt\r\nttttttttttattrttttmtttrttttttrtrrttttttmttrtmtttmjtctttttttt\r\nttttttdcttartmmttrtmmtttmttttrtrrttttttmttrdttrtxjttttmrtttt\r\nttttttttttamtttrttttttrtrdttttttrtttmmttmrttdtmttjtt#ttttttt\r\nttttcttdttarrtttmtttttrtrdttttttmttrtmdtdtrmtrtttjtttmtttttt\r\ntttttttttto######################################ktmtctttttt\r\ntttttttttttttddtttttttttttttmttttttttddttttttttttttttttttttt\r\ntttttttttttttttttttttttttttmtmtttttttttttttttttttttttttttttt\r\ntttrttttttrrttttttttttttttmtttmtttttttttttrrrrtttttttttrtttt\r\nttttttrtttrrtttttttttttttmtttttmttttttttttrrttttttrttrtttttt\r\nttttttttttttttttttrrtttrmttrrrttmttttrtrtttttdttttttrttttttt\r\nttttrtttttrttttttttttttmmmmmmmmmmmttttrtrrrtrtrtttrrtttttttt\r\ntccctttttcccttttctrtttmttttrttrtttmttttcttcctttttccttttttttt\r\nttttrrrrrtrttttttttccmtcttrctcrtcrcmtttcttttttctctcttttttttt\r\n', 150, 20),
(4, 5, 'ttttttttttttttttttttttttttttmttttttttttttttttttttttttttttttt\r\ntttttttttttttttttttttttttttmtmtttttttttttttttttttttttttttttt\r\ntttrttttttrrttttttttttttttmtttmtttttttttttrrrrtttttttttrtttt\r\nttttttrtttrrtttttttttttttmtttttmttttttttttrrttttttrttrtttttt\r\nttttttttttttttttttrrtttrmttrrrttmttttrtrtttttdttttttrttttttt\r\nttttrtttttrttttttttttttmmmmmmmmmmmttttrtrrrtrtrtttrrtttttttt\r\ntccctttttcccttttctrtttmttttrttrtttmttttcttcctttttccttttttttt\r\nttttrrrrrtrttttttttccmtcttrctcrtcrcmtttcttttttctctcttttttttt\r\nttttttttttz######################################wtttttttttt\r\ntttmmrttttammmmmmmmmttttrtrttrttttttttrtmmmmmmmmmjtttttttttt\r\nttttttttttamcccccccctttttttttttrttttrtttccccccccmjtttrrttttt\r\nttttttttttamcdecccccttrttttttttttrtttrttcccccedcmjtttttttttt\r\ntttttmttttammmmmmmmmttrttttttttrttttttrtmmmmmmmmmjtttttcrttt\r\nttttmtmtttamccccccccttttttrtttrtttttttrtccccccccmjtrcttttttt\r\ntttmmmmmttamcdecccccttttrttttttrtrrtttttcccccedcmjttmttttttt\r\nttmrttttmtammmmmmmmmtrrttttttttrtrrtttttmmmmmmmmmjtttttccttt\r\ntmtttttttmamccccccccttttrtrttttrttrtttttccccccccmjttttrttttt\r\ntrrrttttttamcdecccccttttrtrttttrttrttrttcccccedcmjttttttmrtt\r\nttttttttddammmmmmmmmtrrtrttrttttrtttrtttmmmmmmmmmjttcctttttt\r\ntttttcrtttamcccccccctrrtrttrttttttttttttccccccccmjttcrtttttt\r\ntttcctttttamcdecccccttttrttrttttttttrtttcccccedcmjttttrrtttt\r\nttttttttttammmmmmmmmtttttrtttrttttrttrttmmmmmmmmmjtttttttttt\r\nttttttttttattttrtrttrttttttttrtttttrttttttttttttrjtttmmmtttt\r\nttttttttttattttttrttttrttttrttrtrtttrttrtttttttttjtttttttttt\r\nttttrdttttattrttttrtttttrtttrtttttttrttrtttttttttjtttdtttttt\r\nttttttttttattrttttttttrttttttrtrrtttttttttrttttttjtctttttttt\r\nttttttdcttartstttrtttttttttttrtrrtttttttttrrttrtxjttttmrtttt\r\nttttttttttattttrttttttrtrrttttttrttttttttrttrttttjtt#ttttttt\r\nttttcttdttarrtttttttttrtrrtttttttttrttrtrtrttrtttjtttmtttttt\r\ntttttttttto######################################ktmtctttttt\r\ntttttttttttttddtttttttttttttmttttttttddttttttttttttttttttttt\r\ntttttttttttttttttttttttttttmtmtttttttttttttttttttttttttttttt\r\ntttrttttttrrttttttttttttttmtttmtttttttttttrrrrtttttttttrtttt\r\nttttttrtttrrtttttttttttttmtttttmttttttttttrrttttttrttrtttttt\r\nttttttttttttttttttrrtttrmttrrrttmttttrtrtttttdttttttrttttttt\r\nttttrtttttrttttttttttttmmmmmmmmmmmttttrtrrrtrtrtttrrtttttttt\r\ntccctttttcccttttctrtttmttttrttrtttmttttcttcctttttccttttttttt\r\nttttrrrrrtrttttttttccmtcttrctcrtcrcmtttcttttttctctcttttttttt\r\n', 150, 6),
(5, 5, 'ttttttttttttttttttttttttttttmttttttttttttttttttttttttttttttt\r\ntttttttttttttttttttttttttttmtmtttttttttttttttttttttttttttttt\r\ntttrttttttrrttttttttttttttmtttmtttttttttttrrrrtttttttttrtttt\r\nttttttrtttrrtttttttttttttmtttttmttttttttttrrttttttrttrtttttt\r\nttttttttttttttttttrrtttrmttrrrttmttttrtrtttttdttttttrttttttt\r\nttttrtttttrttttttttttttmmmmmmmmmmmttttrtrrrtrtrtttrrtttttttt\r\ntccctttttcccttttctrtttmttttrttrtttmttttcttcctttttccttttttttt\r\nttttrrrrrtrttttttttccmtcttrctcrtcrcmtttcttttttctctcttttttttt\r\nttttttttttz######################################wtttttttttt\r\ntttmmrttttastttttttttttttttttttttttttttttttttttttjtttttttttt\r\nttttttttttattttttttttttttttttttttttttttttttttttttjtttrrttttt\r\nttttttttttattttttttttttttttttttttttttttttttttttttjtttttttttt\r\ntttttmttttattttttttttttttttttttttttttttttttttttttjtttttcrttt\r\nttttmtmtttattttttttttttttttttttttttttttttttttttttjtrcttttttt\r\ntttmmmmmttattttttttttttttttttttttttttttttttttttttjttmttttttt\r\nttmrttttmtattttttttttttttttttttttttttttttttttttttjtttttccttt\r\ntmtttttttmatttttttccEcttttccEcttttccEcttttccEctttjttttrttttt\r\ntrrrttttttatttttttccctttttccctttttccctttttcccttttjttttttmrtt\r\nttttttttddatttttttdcctttttdcctttttdcctttttdccttttjttcctttttt\r\ntttttcrtttattttttttttttttttttttttttttttttttttttttjttcrtttttt\r\ntttcctttttattttttttttttttttttttttttttttttttttttttjttttrrtttt\r\nttttttttttattttttttttttttttttttttttttttttttttttttjtttttttttt\r\nttttttttttatttttttccEcttttccEcttttccEcttttccEctttjtttmmmtttt\r\nttttttttttatttttttccctttttccctttttccctttttcccttttjtttttttttt\r\nttttrdttttatttttttdcctttttdcctttttdcctttttdccttttjtttdtttttt\r\nttttttttttattttttttttttttttttttttttttttttttttttttjtctttttttt\r\nttttttdcttattttttttttttttttttttttttttttttttttttttjttttmrtttt\r\nttttttttttatttttttttttttttttttttttttttttttttttttXjtt#ttttttt\r\nttttcttdttattttttttttttttttttttttttttttttttttttttjtttmtttttt\r\ntttttttttto######################################ktmtctttttt\r\ntttttttttttttddtttttttttttttmttttttttddttttttttttttttttttttt\r\ntttttttttttttttttttttttttttmtmtttttttttttttttttttttttttttttt\r\ntttrttttttrrttttttttttttttmtttmtttttttttttrrrrtttttttttrtttt\r\nttttttrtttrrtttttttttttttmtttttmttttttttttrrttttttrttrtttttt\r\nttttttttttttttttttrrtttrmttrrrttmttttrtrtttttdttttttrttttttt\r\nttttrtttttrttttttttttttmmmmmmmmmmmttttrtrrrtrtrtttrrtttttttt\r\ntccctttttcccttttctrtttmttttrttrtttmttttcttcctttttccttttttttt\r\nttttrrrrrtrttttttttccmtcttrctcrtcrcmtttcttttttctctcttttttttt\r\n', 20, 6),
(8, 5, '###########################\r\n#cccccccccccccccrccccccccc#\r\n#tttttttttttstttcttttttttt#\r\n#tttttttttttttttcttttttttt#\r\n#tttttttttttttttcttttttttt#\r\n#tttttttttttttttcttttttttt#\r\n#tttttttttttttttcttttttttt#\r\n#tttttttttttttttcttttttttt#\r\n#tttttttttttttttcttttttttt#\r\n#tttttttttttttttcttttttttt#\r\n#tttttttttttttttcttttttttt#\r\n#tttttttttttttttcttttttttt#\r\n#tttttttttttttttcttttttttt#\r\n#tttttttttttttttettttttttt#\r\n###########################\r\n', 150, 5);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
